# Generated by Django 3.2.7 on 2021-09-25 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210921_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='dicount',
            new_name='discount',
        ),
    ]
